staging package build
fivetran/dbt_pendo_source pull request #1
Opened 2021-08-13 23:21 UTC by fivetran-jamie

2021-08-16 22:05 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie great job putting this together so quick! I added a few comments and requests for minor formatting changes to address before release. Additionally, I know you had mentioned wanting to update our PR and Issue templates. Was there anything you could think of that we could pilot in this repo?

Once you make the changes it would probably be easiest to just re-request review once you are able to add the README and yml documentation.

2021-08-16 22:05 UTC, fivetran-joemarkiewicz commented on integration_tests/dbt_project.yml
> +
For spark to dispatch effectively we will want to add the dispatch configuration to our integration tests.
```suggestion
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
```

2021-08-16 22:06 UTC, fivetran-joemarkiewicz commented on models/stg_pendo__user.sql
> +        role,
This field being `role`. The comment didn't make it super apparent haha

2021-08-17 16:46 UTC, fivetran-jamie commented on macros/get_page_history_columns.sql
> +{% macro get_page_history_columns() %}
will ask drew...

2021-08-17 17:37 UTC, fivetran-jamie commented on models/tmp/stg_pendo__account_history_tmp.sql
> +select * from {{ var('account_history') }}
ah yeah we should adjust the bash script to automatically align with this

2021-09-02 15:21 UTC, merged